services:
  postgres:
    image: postgres
    container_name: residencia_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: residencia
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
